### ISSUE TITLE
Too many template arguments

### ISSUE THREAD

**Issue by AndreasMartin72** [FlibbleMr/neolib#1]
Hi,

thank you for neolib! :-)
I try to use the neolib::thread class. When compiling I get an error message:
```
neolib\include\neolib\variant.hpp(73) : error C2977: 'boost::variant' : too many template
arguments
        d:/boost_1_60_0/boost/variant/variant.hpp(1085) : see declaration of 'boost::variant'
        ...\neolib\include\neolib\variant.hpp(274) : see reference to class template
        instantiation
        'neolib::variant<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26,T27,T28,T29,T30>'
        being compiled

```
Is this a known issue, or have I missed some settings?
(I'm using MSVC2010)

Kindly regards,
Andreas

**Comment by FlibbleMr** [comment]
Try defining NEOLIB_HOSTED_ENVIRONMENT in your compiler settings; this should increase the Boost MPL parameter limit.

**Comment by AndreasMartin72** [comment]
Yes, this works for me. Thank you!
My version of neolib is quite outdated now, I tried to use a newer version, but got other errors. I will check them. Perhaps I need further help then... 

Kindly regards, 
Andreas
